### ISSUE TITLE
TypeError: undefined is not a function -  $setModelValue("");

### ISSUE THREAD

**Issue by sigismondm** [turinggroup/angular-validator#19]
I checked out the v1.2.2 tag and I whenever I try to run the I get the following error:

    TypeError: undefined is not a function
    at FormController.scopeForm.reset (http://localhost/angular-validator/src/angular-validator.js:27:60)
    at $parseFunctionCall (http://localhost/angular-validator/bower_components/angular/angular.js:12336:18)
    at callback (http://localhost/angular-validator/bower_components/angular/angular.js:21422:17)
    at Scope.$eval (http://localhost/angular-validator/bower_components/angular/angular.js:14388:28)
    at Scope.$apply (http://localhost/angular-validator/bower_components/angular/angular.js:14487:23)
    at HTMLButtonElement.<anonymous> (http://localhost/angular-validator/bower_components/angular/angular.js:21427:23)
    at HTMLButtonElement.eventHandler (http://localhost/angular-validator/bower_components/angular/angular.js:3011:21)angular.js:11598 (anonymous function)angular.js:8548 (anonymous function)angular.js:14489 Scope.$applyangular.js:21427 (anonymous function)angular.js:3011 eventHandler

**Comment by Jakobovski** [comment]
Hi,

I am looking ate line 27 and don't see scopeFrome.reset()... Are you sure you have not made modification to the source?

**Comment by sigismondm** [comment]
Have a look at this https://github.com/turinggroup/angular-validator/blob/v1.2.2/dist/angular-validator.js#L27

**Comment by Jakobovski** [comment]
I see... Thanks for catching this. That code was never meant to be released. Please checkout v1.2.3
